name: segformer
dependencies:
  - python=3.9.7
  - pip=21.2.4
  - pytest=6.2.5
  - pytorch::pytorch=1.10.0
  - pytorch::torchvision=0.11.1
  - cudatoolkit=11.3.1
  - numpy=1.21.2
  - conda-forge::einops=0.3.2
